routes:
  - name: gateway-test
    id: 1
    uri: /hello
    upstream:
      nodes:
        "127.0.0.1:1980": 1
      type: roundrobin
    status: 1

  - name: upstream-test
    id: 2
    uri: /ip
    upstream_id: 1
    status: 1


upstreams:
  - name: httpbin
    id: 1
    nodes:
      "httpbin.org": 1
    type: roundrobin


#END