routes:
  - name: gateway-test
    id: 1
    uri: /hello
    upstream:
      nodes:
        "127.0.0.1:1980": 1
      type: roundrobin
    status: 1

  - name: upstream-test
    id: 2
    uri: /ip
    upstream_id: 1
    status: 1

  - name: frank-test
    id: 3
    uri: /frank-sender
    upstream_id: 1
    plugins:
      proxy-rewrite:
        uri: /any
      frank-sender:
        frank_endpoint: http://host.docker.internal:8080/api/frank-test

upstreams:
  - name: httpbun
    id: 1
    nodes:
      "httpbun.com": 1
    type: roundrobin

#END