deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
apisix:
  extra_lua_path: "/usr/local/apisix/custom-plugins/?.lua"
  extra_lua_cpath: "/usr/local/apisix/custom-plugin-libs/?.so"
  enable_control: true
  control:
    ip: "127.0.0.1"
    port: 9090
plugins: 
  - fsc
  - file-logger
nginx_config:
  error_log_level: debug
  http_configuration_snippet: |
      # TODO this is used for both the FSC plugin as well as the openid-connect plugin, need to test if this causes conflicts
      lua_shared_dict discovery             1m; # cache for discovery metadata documents
      lua_shared_dict jwks                  1m; # cache for JWKs
      lua_shared_dict introspection        10m; # cache for JWT verification results