deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
apisix:
  extra_lua_path: "/usr/local/apisix/custom-plugins/?.lua"
  extra_lua_cpath: "/usr/local/apisix/custom-plugin-libs/?.so"
  enable_control: true
  control:
    ip: "127.0.0.1"
    port: 9090
  ssl:
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    # fallback_sni: "localhost"
plugins: 
  - fsc
  - file-logger
nginx_config:
  error_log_level: debug
  http_configuration_snippet: |
      # TODO this is used for both the FSC plugin as well as the openid-connect plugin, need to test if this causes conflicts
      lua_shared_dict discovery             1m; # cache for discovery metadata documents
      lua_shared_dict jwks                  1m; # cache for JWKs
      lua_shared_dict introspection        10m; # cache for JWT verification results