apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ./resources/namespace.yaml

helmCharts:
  - name: apisix
    releaseName: apisix
    repo: https://charts.apiseven.com
    valuesFile: values.yaml
    namespace: ingress-apisix
    includeCRDs: true