#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: frank-gateway-test # Name of the parent container
services:
  apisix:
    image: ghcr.io/wearefrank/frank-gateway:master
    restart: always
    volumes:
      - ./apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      - "9080:9080/tcp"
  
    networks:
      apisix:
      
  httpbun:
    image: sharat87/httpbun:8cb6c4f90cf49eb4509e7ae699c27b9f85f383c5
    restart: always
    ports:
      - "80:80/tcp"
    networks:
      apisix:

  opa:
    image: openpolicyagent/opa:1.9.0-static # version bundled in opal-client 0.9.3, matches gemeente utrecht
    restart: always
    command: ["run", "--server", "--config-file", "/opa-config.yaml", "--addr", ":8181", "/policies"]
    volumes:
      - ./policies:/policies
    ports:
      - "8181:8181/tcp"
    configs:
      - source: opa-config.yaml
        target: /opa-config.yaml
    networks:
      apisix:
    

configs:
  # Hierdoor gaat hij de logs in de console weergeven, dit kan gebruikt worden voor logging 
  opa-config.yaml:
    content: |
      decision_logs:
        console: true


networks:
  apisix:
    driver: bridge