# httpbin-route.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
  - name: fooRule
    match:
      paths:
        - /foo/*
    backends:
       - serviceName: foo-service
         servicePort: 8080
    plugins:
      - name: prometheus
        enable: true
        config:
          prefer_name: true
      - name: openid-connect
        enable: true
        config:
          client_id: apisix
          client_secret: WxUoCcLdNGJnYHxg4QkpEFNQ39GU5Ahz
          discovery: http://keycloak.iam.svc.cluster.local:8080/realms/apisix_test_realm/.well-known/openid-configuration
          scope: "openid profile"
          bearer_only: false
          realm: apisix_test_realm
          introspection_endpoint_auth_method: client_secret_post
          redirect_uri: http://localhost/foo/
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/foo/(.*)","/$1"]
  - name: barRule
    match: 
      paths: 
      - /bar/*
    backends: 
      - serviceName: bar-service
        servicePort: 8080
    plugins:
      - name: prometheus
        enable: true
        config:
          prefer_name: true
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/bar/(.)", "/$1"]
      - name: openid-connect
        enable: true
        config:
          client_id: apisix
          client_secret: WxUoCcLdNGJnYHxg4QkpEFNQ39GU5Ahz
          discovery: http://keycloak.iam.svc.cluster.local:8080/realms/apisix_test_realm/.well-known/openid-configuration
          bearer_only: true
          realm: apisix_test_realm
          use_jwks: true
          # introspection_endpoint: http://keycloak.iam.svc.cluster.local:8080/realms/apisix_test_realm/protocol/openid-connect/token/introspect
          # introspection_endpoint_auth_method: client_secret_basic